### ISSUE TITLE
Add support for other font types

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-font#14]
As per https://github.com/simple-icons/simple-icons/issues/1540#issuecomment-512744777, what are our options of adding support for `.ttf`, `.woff`, `.woff2` (and other?) font types?

**Comment by metaa** [comment]
With the `icon-font-buildr` [output options](https://github.com/simple-icons/simple-icons-font/blob/83798b8a737ae9e88e73f2b75fc331a6cc21937a/scripts/build.js#L29) we can supply these formats:

```js
formats: [ // Font formats to output
    'eot',
    'ttf',
    'woff',
    'woff2'
]
```

**Comment by ericcornelissen** [comment]
When I try `.ttf` the font is not working in Chrome `75.0.3770.142` (64 bits) nor Firefox `68.0` (64-bit) nor Edge `44.18362.1.0` (Microsoft EdgeHTML `18.18362`) and it looks like ⬇️ Interestingly the `woff`/`woff2` version looks the same in Firefox (both Chrome and Edge work fine).

![image](https://user-images.githubusercontent.com/3742559/61684023-cb64b400-ad0f-11e9-9e33-b00290414d12.png)

When I changed the `font.css` file to

```css
@font-face {
  font-family: 'Simple Icons';
  src: url(SimpleIcons.ttf) format('truetype');
}
```

With `.eot` it only works in Edge, but it's generally a fallback for Internet Explorer(?) so it would be nice to have it tested there...

```css
@font-face {
  font-family: 'Simple Icons';
  src: url(SimpleIcons.eot);
}
```
