### ISSUE TITLE
Set cron job as fallback for automated releases

### ISSUE THREAD

**Issue by mondeja** [simple-icons/simple-icons-font#231]
The automated release triggered by main repository has failed this week, see https://github.com/simple-icons/simple-icons-font/actions/runs/15232588759/job/42842250496

This has caused that the simple-icons-font v14.15.0 has not been released until today, Friday. We need to set the same cron job that is configured in the website. Using this, in case that the triggered workflow run fails, one or two days after, a scheduled release runs.

```yaml
name: Automated Releases
on:
  schedule:
    - cron: 0 0 * * 1,3,5
  workflow_dispatch:
```
